/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.UserUI;

import BLL.ExecuteData;
import BLL.GetData;
import GUI.SystemForm;
import javax.swing.JOptionPane;

/**
 *
 * @author phatl
 */
public class EditUser extends javax.swing.JFrame {

    /**
     * Creates new form EditUser
     */
    public String user = null;
    public SystemForm root = null;
    
    
    public EditUser() {
        initComponents();
        loadProfile();
        loadRole();
    }

    
    @SuppressWarnings("unchecked")
    private void loadProfile(){
        //load combobox list name profile
        GetData x = new GetData();
        cb_Profile.removeAllItems();
        Object[][] nameProfiles = x.getAllProfileName();
        int n = nameProfiles.length;
        for(int i =0;i<n;i++)
        {
            cb_Profile.addItem(nameProfiles[i][0].toString());
        }
    }
    private void loadRole(){
        //load combobox list name profile
        GetData x = new GetData();
        cb_role.removeAllItems();
        Object[][] nameRole = x.getNameRole();
        int n = nameRole.length;
        for(int i =n-1;i>=0;i--)
        {
            cb_role.addItem(nameRole[i][0].toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_Profile = new Ultilities.swing.Controls.ComboBoxSuggestion();
        btn_Luu = new Ultilities.swing.Controls.ButtonGradient();
        btn_Huy = new Ultilities.swing.Controls.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        cb_role = new Ultilities.swing.Controls.ComboBoxSuggestion();
        btn_thuhoi = new Ultilities.swing.Controls.ButtonGradient();
        ck_adminoption = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT USER");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 15, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROFILE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);
        jPanel2.add(cb_Profile);

        btn_Luu.setForeground(new java.awt.Color(0, 0, 0));
        btn_Luu.setText("Lưu");
        btn_Luu.setColor1(new java.awt.Color(153, 255, 153));
        btn_Luu.setColor2(new java.awt.Color(153, 255, 255));
        btn_Luu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.setColor1(new java.awt.Color(255, 153, 153));
        btn_Huy.setFocusPainted(false);
        btn_Huy.setFocusable(false);
        btn_Huy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ROLE");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_thuhoi.setForeground(new java.awt.Color(0, 0, 0));
        btn_thuhoi.setText("Thu hồi");
        btn_thuhoi.setColor1(new java.awt.Color(153, 255, 153));
        btn_thuhoi.setColor2(new java.awt.Color(153, 255, 255));
        btn_thuhoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_thuhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuhoiActionPerformed(evt);
            }
        });

        ck_adminoption.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ck_adminoption.setText("with admin option");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_thuhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ck_adminoption)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(ck_adminoption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thuhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        if(ck_adminoption.isSelected())
        {
            if(ExecuteData.EditProfileOfUser(user, cb_Profile.getSelectedItem().toString()) && ExecuteData.GrantRoleOfUserAdminOption(user, cb_role.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(this,"Cập nhật thông tin "+ user +" thành công !");
            root.loadUserData();
            }
            else
                JOptionPane.showMessageDialog(this,"Cập nhật thông tin "+ user +" thất bại !");
        }
        else
        {
            if(ExecuteData.EditProfileOfUser(user, cb_Profile.getSelectedItem().toString()) && ExecuteData.GrantRoleOfUser(user, cb_role.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(this,"Cập nhật thông tin "+ user +" thành công !");
                root.loadUserData();
            }
            else
                JOptionPane.showMessageDialog(this,"Cập nhật thông tin "+ user +" thất bại !");
        }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_thuhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuhoiActionPerformed
        // TODO add your handling code here:
        if(ExecuteData.RevokeRole( cb_role.getSelectedItem().toString(),user))
        {
            JOptionPane.showMessageDialog(this,"Thu hồi role "+ cb_role.getSelectedItem().toString() + " của "+ user +" thành công !");
            root.loadUserData();
        }
        else
            JOptionPane.showMessageDialog(this,"Thu hồi role của "+ user +" thất bại !");
    
    }//GEN-LAST:event_btn_thuhoiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.ButtonGradient btn_Huy;
    private Ultilities.swing.Controls.ButtonGradient btn_Luu;
    private Ultilities.swing.Controls.ButtonGradient btn_thuhoi;
    private Ultilities.swing.Controls.ComboBoxSuggestion cb_Profile;
    private Ultilities.swing.Controls.ComboBoxSuggestion cb_role;
    private javax.swing.JCheckBox ck_adminoption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
