/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.HoaDon;
import BLL.CallExecute;
import BLL.ExecuteData;
import BLL.UpdateData;
import BLL.GetData;
import BLL.GetValue;
import com.sun.source.tree.BreakTree;
import java.util.ArrayList;
import java.awt.Color;
import java.awt.Component;
import java.security.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import oracle.jdbc.driver.Message;
import com.toedter.calendar.JDateChooser;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import javax.xml.bind.DatatypeConverter;
import java.beans.PropertyChangeListener;
import java.text.DecimalFormat;
/**
 *
 * @author ASUS
 */
public class CHITIETHOADON extends javax.swing.JPanel {
    private GetData x = new GetData();
    private UpdateData t  = new UpdateData();
    private GetValue y = new GetValue();
    private int demSoLanThem = 0;
    private int demSoLanCapNhat = 0;
    private  int demSoLanXoa = 0;
    /**
     * Creates new form CHITIETHOADON
     */
    public CHITIETHOADON() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_CTHD = new javax.swing.JTable();
        btn_themcthd = new javax.swing.JButton();
        btn_showCTHD = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_sl = new javax.swing.JTextField();
        txt_macthd = new javax.swing.JTextField();
        txt_macthdtd = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jp5.setBackground(new java.awt.Color(255, 255, 255));

        table_CTHD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(table_CTHD);

        btn_themcthd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_themcthd.setText("Thêm");
        btn_themcthd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themcthdMouseClicked(evt);
            }
        });

        btn_showCTHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_showCTHD.setText("Refresh");
        btn_showCTHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showCTHDMouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 0));
        jLabel29.setText("Số Lượng");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 0));
        jLabel30.setText("Mã Hóa Đơn");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 0));
        jLabel31.setText("Mã Thực Đơn");

        txt_sl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_macthd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_macthdtd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_showCTHD)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp5Layout.createSequentialGroup()
                                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addGroup(jp5Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(71, 71, 71)
                                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_sl, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                                            .addComponent(txt_macthd)
                                            .addComponent(txt_macthdtd)
                                            .addGroup(jp5Layout.createSequentialGroup()
                                                .addGap(239, 239, 239)
                                                .addComponent(btn_themcthd)))))
                                .addContainerGap(447, Short.MAX_VALUE))
                            .addGroup(jp5Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jp5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 373, Short.MAX_VALUE))))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_showCTHD)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_macthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_macthdtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_themcthd)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themcthdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themcthdMouseClicked
        // TODO add your handling code here:
        if ( txt_sl.getText().isEmpty() || txt_macthd.getText().isEmpty() || txt_macthdtd.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanThem < 100) {
                if (CallExecute.insertCTHD(txt_sl.getText(), txt_macthd.getText(),txt_macthdtd.getText())) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_sl.setText("");
                    txt_macthd.setText("");
                    txt_macthdtd.setText("");
                    if (demSoLanThem >= 100) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_themcthdMouseClicked

    private void btn_showCTHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showCTHDMouseClicked
        // TODO add your handling code here:
        ArrayList arr = null;
        DefaultTableModel model = (DefaultTableModel) table_CTHD.getModel();
        if (arr == null) {
            arr = x.showDataCTHD();
        }

        Object[] columnNames = (Object[]) arr.get(0);
        Object[][] data = (Object[][]) arr.get(1);

        model.setDataVector(data, columnNames);
    }//GEN-LAST:event_btn_showCTHDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_showCTHD;
    private javax.swing.JButton btn_themcthd;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jp5;
    private javax.swing.JTable table_CTHD;
    private javax.swing.JTextField txt_macthd;
    private javax.swing.JTextField txt_macthdtd;
    private javax.swing.JTextField txt_sl;
    // End of variables declaration//GEN-END:variables
}
