/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.HoaDon;

import BLL.CallExecute;
import BLL.ExecuteData;
import BLL.UpdateData;
import BLL.GetData;
import BLL.GetValue;
import com.sun.source.tree.BreakTree;
import java.util.ArrayList;
import java.awt.Color;
import java.awt.Component;
import java.security.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import oracle.jdbc.driver.Message;
import com.toedter.calendar.JDateChooser;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import javax.xml.bind.DatatypeConverter;
import java.beans.PropertyChangeListener;
import java.text.DecimalFormat;

/**
 *
 * @author ASUS
 */
public class QLHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form QLHoaDon
     */
    private GetData x = new GetData();
    private UpdateData t  = new UpdateData();
    private GetValue y = new GetValue();
    private int demSoLanThem = 0;
    private int demSoLanCapNhat = 0;
    private  int demSoLanXoa = 0;
    private JDateChooser dateChooser;
    
    public QLHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_HD = new javax.swing.JTable();
        btn_SuaHD = new javax.swing.JButton();
        btn_themHD = new javax.swing.JButton();
        btn_showHD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_MAHD = new javax.swing.JTextField();
        txt_HTTT = new javax.swing.JTextField();
        txt_MANV = new javax.swing.JTextField();
        txt_MAKM = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        txt_MAKH = new javax.swing.JTextField();
        btn_Date = new com.toedter.calendar.JDateChooser();
        btn_xoaHD = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jp2.setBackground(new java.awt.Color(255, 255, 255));

        table_HD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_HD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_HD);

        btn_SuaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_SuaHD.setText("Cập Nhật");
        btn_SuaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuaHDMouseClicked(evt);
            }
        });

        btn_themHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_themHD.setText("Thêm");
        btn_themHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themHDMouseClicked(evt);
            }
        });

        btn_showHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_showHD.setText("Refresh");
        btn_showHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showHDMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("MAHD");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Ngày Lập");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Hình Thức Thanh Toán");

        jLabel9.setFont(new java.awt.Font("VNtimes new roman", 0, 18)); // NOI18N
        jLabel9.setText("MAKH");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("MAKM");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("MANV");

        jTextField6.setText("jTextField1");

        jTextField7.setText("jTextField1");

        btn_xoaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_xoaHD.setText("Xóa");
        btn_xoaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaHDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_showHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(122, 122, 122)))
                        .addGap(7, 7, 7)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_HTTT)
                                .addComponent(txt_MAKM)
                                .addComponent(txt_MANV)
                                .addComponent(txt_MAHD)
                                .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_SuaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_themHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_xoaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(235, 235, 235)))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                    .addContainerGap(409, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(225, 225, 225)))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_showHD)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_HTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_MAKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_MANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(txt_MAHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(btn_SuaHD)
                                .addGap(17, 17, 17)
                                .addComponent(btn_themHD)))
                        .addGap(18, 18, 18)
                        .addComponent(btn_xoaHD)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp2Layout.createSequentialGroup()
                    .addGap(348, 348, 348)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(352, Short.MAX_VALUE)))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                    .addContainerGap(182, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(342, 342, 342)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SuaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuaHDMouseClicked
        // TODO add your handling code here:
        Date date = null;
        if (btn_Date != null) {
            date = btn_Date.getDate();
        }
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày tháng năm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (txt_HTTT.getText().isEmpty() || txt_MAKH.getText().isEmpty() || txt_MAKM.getText().isEmpty() || txt_MANV.getText().isEmpty() || txt_MAHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            if (demSoLanCapNhat < 2) {
                if (CallExecute.updateHD(dateFormat.format(date), txt_HTTT.getText(), txt_MAKH.getText(), txt_MAKM.getText(), txt_MANV.getText(), txt_MAHD.getText())) {
                    demSoLanCapNhat++;

                    JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_MAHD.setText("");
                    btn_Date.setDate(null);
                    txt_HTTT.setText("");
                    txt_MAKH.setText("");
                    txt_MAKM.setText("");
                    txt_MANV.setText("");

                    if (demSoLanCapNhat >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công 2 lần và bạn không cập nhật được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn cập nhật (2 lần). Không thể cập nhật.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_SuaHDMouseClicked

    private void btn_themHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themHDMouseClicked
        // TODO add your handling code here:
        if(txt_HTTT.getText().isEmpty() || txt_MAKH.getText().isEmpty() || txt_MAKM.getText().isEmpty() || txt_MANV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanThem < 1000) {
                if (CallExecute.insertHD(txt_HTTT.getText(), txt_MAKH.getText(), txt_MAKM.getText(), txt_MANV.getText())) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_HTTT.setText("");
                    txt_MAKH.setText("");
                    txt_MAKM.setText("");
                    txt_MANV.setText("");

                    if (demSoLanThem >= 1000) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);

                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_themHDMouseClicked

    private void btn_showHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showHDMouseClicked
        ArrayList arr = null;
        DefaultTableModel model = (DefaultTableModel) table_HD.getModel();
        if (arr == null) {
            arr = x.showDataHoaDon();
        }

        Object[] columnNames = (Object[]) arr.get(0);
        Object[][] data = (Object[][]) arr.get(1);

        model.setDataVector(data, columnNames);
        // Lấy đối tượng cell renderer của cột ngày tạo hóa đơn
        TableColumnModel columnModel = table_HD.getColumnModel();
        TableColumn column = columnModel.getColumn(1); // ví dụ cột 2 là cột ngày tạo hóa đơn
        TableCellRenderer renderer = new DefaultTableCellRenderer();

        // Định dạng lại ngày tháng năm cho cell renderer
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        ((DefaultTableCellRenderer) renderer).setHorizontalAlignment(JLabel.CENTER);

        // Thiết lập giá trị mới cho cell renderer
        column.setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) renderer.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (value instanceof Date) {
                    label.setText(dateFormat.format(value));
                }
                return label;
            }
        });
    }//GEN-LAST:event_btn_showHDMouseClicked

    private void btn_xoaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaHDMouseClicked
        // TODO add your handling code here:
        int row = table_HD.getSelectedRow ();
        int col = 0;
        if(CallExecute.deleteHD(table_HD.getValueAt (row,col).toString ()))
        {
            JOptionPane.showMessageDialog(this, "Xóa Hóa Đơn thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Thất bại","Lỗi Xóa",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_xoaHDMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser btn_Date;
    private javax.swing.JButton btn_SuaHD;
    private javax.swing.JButton btn_showHD;
    private javax.swing.JButton btn_themHD;
    private javax.swing.JButton btn_xoaHD;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel jp2;
    private javax.swing.JTable table_HD;
    private javax.swing.JTextField txt_HTTT;
    private javax.swing.JTextField txt_MAHD;
    private javax.swing.JTextField txt_MAKH;
    private javax.swing.JTextField txt_MAKM;
    private javax.swing.JTextField txt_MANV;
    // End of variables declaration//GEN-END:variables
}
