package GUI;

import java.awt.Color;
import DAL.DBConfig;
import BLL.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import Ultilities.ConvertData.*;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.BasicConfigurator;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        BasicConfigurator.configure();
        chk_showHidePass.setBackground(new Color(0, 0, 0, 0));
        this.getRootPane().setDefaultButton(cmdLogin);
    }
    
    public void hideLogin()
    {
        this.setVisible(false);
    }
    
    public void showLogin()
    {
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new Ultilities.login.Background();
        panel = new javax.swing.JPanel();
        txtUser = new Ultilities.swing.Controls.TextField();
        txtPassword = new Ultilities.swing.Controls.PasswordField();
        jLabel1 = new javax.swing.JLabel();
        cmdLogin = new Ultilities.swing.Controls.Button();
        buttonCustom1 = new Ultilities.swing.Controls.buttonCustom();
        Scan_QR = new javax.swing.JLabel();
        chk_showHidePass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBlur(panel);

        panel.setBackground(new java.awt.Color(0, 0, 0));
        panel.setOpaque(false);

        txtUser.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUser.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtUser.setHint("User Name");

        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setDragEnabled(true);
        txtPassword.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtPassword.setHint("Password");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");

        cmdLogin.setForeground(new java.awt.Color(231, 231, 231));
        cmdLogin.setText("LOGIN");
        cmdLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });

        buttonCustom1.setBorder(null);
        buttonCustom1.setForeground(new java.awt.Color(255, 255, 255));
        buttonCustom1.setText("CANCEL");
        buttonCustom1.setBorderColor(new java.awt.Color(255, 51, 51));
        buttonCustom1.setColorClick(new java.awt.Color(255, 51, 51));
        buttonCustom1.setColorOver(new java.awt.Color(255, 102, 102));
        buttonCustom1.setFocusPainted(false);
        buttonCustom1.setFocusable(false);
        buttonCustom1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustom1ActionPerformed(evt);
            }
        });

        Scan_QR.setBackground(new java.awt.Color(255, 255, 255));
        Scan_QR.setForeground(new java.awt.Color(255, 255, 255));
        Scan_QR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Scan_QR.setText("Scan QR");
        Scan_QR.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Scan_QR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Scan_QRMouseClicked(evt);
            }
        });

        chk_showHidePass.setBackground(new java.awt.Color(255, 0, 204));
        chk_showHidePass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chk_showHidePass.setForeground(new java.awt.Color(255, 255, 255));
        chk_showHidePass.setText("Show");
        chk_showHidePass.setFocusPainted(false);
        chk_showHidePass.setFocusable(false);
        chk_showHidePass.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chk_showHidePass.setOpaque(true);
        chk_showHidePass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chk_showHidePassItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(Scan_QR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(chk_showHidePass))
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Scan_QR)
                    .addComponent(chk_showHidePass))
                .addGap(17, 17, 17)
                .addComponent(cmdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        //new Dashboard().setVisible(true);
        String user = txtUser.getText();
        String pass = String.valueOf(txtPassword.getPassword());
        if(user.length() == 0 || pass.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !","Thông Báo",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            signinDB (user,pass);            
        }
        
        
    }//GEN-LAST:event_cmdLoginActionPerformed
    protected boolean signinDB(String user, String pass)
    {    
        this.setVisible(false);
        DBConfig.username = user;
        DBConfig.password = pass;
        Connection conn = DBConfig.getConnectionString();
        DBConfig.testgetConnect();
        try{
            DBConfig.Connect = conn;
            conn.createStatement();
            
            this.setVisible(false);
            Dashboard dash = new Dashboard(user);
            dash.setVisible(true);
            Dashboard.conn = conn;
            Dashboard.loginForm = this;
            
            JOptionPane.showMessageDialog(this, "Đăng nhập Thành Công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
            return true;
        }
        catch(Exception err){
            JOptionPane.showMessageDialog(this, "Đăng nhập thất bại !","Lỗi Đăng Nhập",JOptionPane.ERROR_MESSAGE);
            this.setVisible(true);
            System.out.println(err.getMessage());
            return false;
        }
    }
    
    private void buttonCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustom1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonCustom1ActionPerformed

    private void Scan_QRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Scan_QRMouseClicked
        // TODO add your handling code here:
        new Scan_QR (this).setVisible (true);
        
    }//GEN-LAST:event_Scan_QRMouseClicked

    private void chk_showHidePassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chk_showHidePassItemStateChanged
        if(evt.getStateChange() == 1)
        {
            txtPassword.setEchoChar((char)0);
        }
        else
        {
            txtPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_chk_showHidePassItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Scan_QR;
    private Ultilities.login.Background background;
    private Ultilities.swing.Controls.buttonCustom buttonCustom1;
    private javax.swing.JCheckBox chk_showHidePass;
    private Ultilities.swing.Controls.Button cmdLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private Ultilities.swing.Controls.PasswordField txtPassword;
    private Ultilities.swing.Controls.TextField txtUser;
    // End of variables declaration//GEN-END:variables
}
