/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.UpdateData;
import BLL.GetData;
import BLL.GetValue;
import java.io.File;
import java.util.ArrayList;
import java.awt.desktop.OpenFilesEvent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import oracle.jdbc.driver.Message;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC THAO
 */
public class S_Tablespaces
        extends javax.swing.JFrame {
    private ArrayList arr;
    private GetData x ;
    private UpdateData t;
    private GetValue y;
    /**
     * Creates new form S_Tablespaces
     */
    public S_Tablespaces() {
        initComponents ();
        x = new GetData();
        y = new GetValue ();
        t = new UpdateData ();
        initValue ();
        setLocationRelativeTo (null);
        showDataOnTable();
       
    }
    private void initValue()
    {
        lbl_SumDatafile.setText (y.sumTablespaces());
        lbl_SumTablespace.setText (y.sumDataFile ());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Linkfile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Size = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_Resize = new javax.swing.JButton();
        btn_openFile = new javax.swing.JButton();
        btn_addDatafile = new javax.swing.JButton();
        btn_removeDatafile = new javax.swing.JButton();
        txt_Disk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdo_existDatafile = new javax.swing.JRadioButton();
        rdo_newDatafile = new javax.swing.JRadioButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Tablespace = new javax.swing.JTable();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        btn_removetablespace = new javax.swing.JButton();
        rdo_Tablespace = new javax.swing.JRadioButton();
        rdo_tablespaceDatafile = new javax.swing.JRadioButton();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btn_create = new javax.swing.JButton();
        btn_changeName = new javax.swing.JButton();
        lbl_SumDatafile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Nametablespace = new javax.swing.JTextField();
        lbl_SumTablespace = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbb_showTablespace = new javax.swing.JComboBox<>();
        btn_ShowDatafile = new javax.swing.JButton();

        jButton6.setText("jButton6");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Datafile");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 77, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Đường dẫn");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 20));
        jPanel2.add(txt_Linkfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 340, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Size");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 37, 20));
        jPanel2.add(txt_Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 30));

        jLabel7.setText("MB");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 37, 40));

        btn_Resize.setText("Resize");
        btn_Resize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ResizeMouseClicked(evt);
            }
        });
        jPanel2.add(btn_Resize, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 89, 30));

        btn_openFile.setText("Open file");
        btn_openFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_openFileMouseClicked(evt);
            }
        });
        jPanel2.add(btn_openFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 89, 30));

        btn_addDatafile.setText("Thêm datafile");
        btn_addDatafile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_addDatafileMouseClicked(evt);
            }
        });
        jPanel2.add(btn_addDatafile, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 131, 40));

        btn_removeDatafile.setText("Xóa datafile");
        btn_removeDatafile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_removeDatafileMouseClicked(evt);
            }
        });
        jPanel2.add(btn_removeDatafile, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 131, 40));

        txt_Disk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiskActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Disk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ổ đĩa");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        buttonGroup2.add(rdo_existDatafile);
        rdo_existDatafile.setText("Datafile đã tồn tại");
        jPanel2.add(rdo_existDatafile, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 140, -1));

        buttonGroup2.add(rdo_newDatafile);
        rdo_newDatafile.setText("Datafile mới");
        jPanel2.add(rdo_newDatafile, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        jDesktopPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Table_Tablespace.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_Tablespace);

        jDesktopPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_removetablespace.setText("Xóa");
        btn_removetablespace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_removetablespaceMouseClicked(evt);
            }
        });

        buttonGroup1.add(rdo_Tablespace);
        rdo_Tablespace.setText("Tablespace");

        buttonGroup1.add(rdo_tablespaceDatafile);
        rdo_tablespaceDatafile.setText("Tablespace và datafile");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_removetablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_tablespaceDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_Tablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rdo_Tablespace)
                .addGap(18, 18, 18)
                .addComponent(rdo_tablespaceDatafile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_removetablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jDesktopPane6.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_create.setBackground(new java.awt.Color(153, 255, 255));
        btn_create.setText("Tạo");
        btn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_createMouseClicked(evt);
            }
        });

        btn_changeName.setBackground(new java.awt.Color(153, 255, 255));
        btn_changeName.setText("Đổi tên");
        btn_changeName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_changeNameMouseClicked(evt);
            }
        });

        lbl_SumDatafile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SumDatafile.setText(".");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tổng dung lượng datafile:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tổng dung lượng Tablespace:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tên");

        lbl_SumTablespace.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SumTablespace.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Nametablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(btn_changeName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_SumDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_SumTablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SumDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SumTablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nametablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_changeName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jDesktopPane7.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABLESPACES");

        cbb_showTablespace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hiển thị danh sách", "Hiển thị dung lượng còn trống", "Hiển thị tên và dung lượng" }));
        cbb_showTablespace.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_showTablespaceItemStateChanged(evt);
            }
        });

        btn_ShowDatafile.setText("Refresh");
        btn_ShowDatafile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ShowDatafileMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDesktopPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_ShowDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbb_showTablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_showTablespace, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ShowDatafile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Hiện thị dữ liệu
    public void showDataOnTable()
        {
            DefaultTableModel model = (DefaultTableModel)Table_Tablespace.getModel();
            if(arr == null)
            {
                 this.arr = x.showTablespaces();
            }
            Object[] columnNames = (Object[])this.arr.get(0);
            Object[][] data = (Object[][])this.arr.get(1);

            model.setDataVector (data,columnNames);
        }
    //Hiển thị theo combobox
    private void cbb_showTablespaceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_showTablespaceItemStateChanged
        // TODO add your handling code here:
        String cb1 = "Hiển thị dung lượng còn trống";
        String cb2 = "Hiển thị danh sách";
        if(  cbb_showTablespace.getSelectedItem().toString().equals (cb2))
        {
            arr = x.showTablespaces ();
        }
        else
        {
            if(cbb_showTablespace.getSelectedItem().toString().equals (cb1))
            {
                arr = x.showFreeSpace ();
            }
            else
            {
                arr = x.showNameAndContent ();
            }
        }
        showDataOnTable();
    }//GEN-LAST:event_cbb_showTablespaceItemStateChanged
   
    
    
    // <editor-fold defaultstate="collapsed" desc="Tạo tablespace">  //Tạo tablespace
    private void btn_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_createMouseClicked
        // TODO add your handling code here:
        if(txt_Nametablespace.getText ().isEmpty ()||txt_Linkfile.getText ().isEmpty () || txt_Size.getText ().isEmpty ())
        {
             JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Bạn hãy đặt tên nhé","Lỗi tên",JOptionPane.ERROR_MESSAGE);
          
        }
        else
        {
            if(t.createTablespace (txt_Nametablespace.getText (), txt_Linkfile.getText (), txt_Size.getText ()))
            {
                JOptionPane.showMessageDialog(this, "Tạo tablespace thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                txt_Nametablespace.setText ("");
                txt_Linkfile.setText ("");
                txt_Size.setText ("");
                arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thất bại","Lỗi tạo",JOptionPane.ERROR_MESSAGE);
            }     
        }
    }//GEN-LAST:event_btn_createMouseClicked
    // </editor-fold>
    
    
    // <editor-fold defaultstate="collapsed" desc="Đổi tên tablespace">  //
    private void btn_changeNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_changeNameMouseClicked
        // TODO add your handling code here:
        int row = Table_Tablespace.getSelectedRow ();
         if(txt_Nametablespace.getText ().isEmpty ())
        {
            JOptionPane.showMessageDialog(this, "Lỗi tên đang bị trống! Bạn hãy đặt tên nhé","Lỗi tên",JOptionPane.ERROR_MESSAGE);
        }else
         {
              if(row < 0)
                {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn tên tablespace muốn đổi!","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                       return;
                }
              if(t.changeNameTablespace (Table_Tablespace.getValueAt (row,0).toString (),txt_Nametablespace.getText()))
              {
                 JOptionPane.showMessageDialog(this, "Đổi tên thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                 txt_Nametablespace.setText ("");
                 arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
              }
              else
              {
                  JOptionPane.showMessageDialog(this, "Thất bại","Lỗi tạo",JOptionPane.ERROR_MESSAGE);
              }
         }

    }//GEN-LAST:event_btn_changeNameMouseClicked
    // </editor-fold>  
    

    // <editor-fold defaultstate="collapsed" desc="Lấy đường dẫn datafile"> //Lấy đường dẫn datafile
    private JFileChooser openFileChooser;
    private String absolutePath = null;
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Open file">
    private void btn_openFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_openFileMouseClicked
        // TODO add your handling code here:
        if(txt_Disk.getText ().isEmpty ())
        {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn ổ đĩa","Lỗi tên",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            openFileChooser = new JFileChooser(); 
            openFileChooser.setCurrentDirectory (new File(txt_Disk.getText () + ":\\"));
            openFileChooser.setFileFilter (new FileNameExtensionFilter("",".dbf"));
            int returnvalue = openFileChooser.showOpenDialog (this);
            if(returnvalue == JFileChooser.APPROVE_OPTION)
            {
                File file = openFileChooser.getSelectedFile ();
                absolutePath = file.getAbsolutePath();
                txt_Linkfile.setText (absolutePath);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn đường dẫn","Lỗi tạo",JOptionPane.ERROR_MESSAGE);

            }
        }
        
    }//GEN-LAST:event_btn_openFileMouseClicked
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Thêm datafile vào tablespace">//Thêm datafile  vào tablespace
    private void btn_addDatafileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addDatafileMouseClicked
        // TODO add your handling code here:
        
        if( absolutePath.isBlank () || absolutePath.isEmpty ())
        {
             
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn file","Thông báo",JOptionPane.ERROR_MESSAGE);
            
        }
        else
        {
            int row = Table_Tablespace.getSelectedRow ();
             if(row < 0)
                {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn tên tablespace !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                       return;
                }
            if(rdo_existDatafile.isSelected ())
            {
               
                if(t.addDataFileExistTablespace ( Table_Tablespace.getValueAt (row,0).toString (),txt_Linkfile.getText()))
                {
                     JOptionPane.showMessageDialog(this, "Thêm datafile đã tồn tại thành công!","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                     arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
                }
                else
                    JOptionPane.showMessageDialog(this, "Thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                
                 if(t.addDataFileTablespace ( Table_Tablespace.getValueAt (row,0).toString (),txt_Linkfile.getText(), txt_Size.getText ()))
                {
                     JOptionPane.showMessageDialog(this, "Thêm datafile thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                     arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
                }
                else
                    JOptionPane.showMessageDialog(this, "Thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
                
        }
    }//GEN-LAST:event_btn_addDatafileMouseClicked
    // </editor-fold> 
    
    //Xóa tablespace và datafile
    private void btn_removetablespaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removetablespaceMouseClicked
        // TODO add your handling code here:
        int row = Table_Tablespace.getSelectedRow ();
         if(row < 0)
                {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn tên tablespace !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                       return;
                }
        if(rdo_Tablespace.isSelected())
        {
            if(t.dropTablespace (Table_Tablespace.getValueAt (row,0).toString ()))
            {
                 JOptionPane.showMessageDialog(this, "Xóa tablespace thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                 arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
            }
            else
                JOptionPane.showMessageDialog(this, "Thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
        }else
        {
            if(t.dropAllTablespace (Table_Tablespace.getValueAt (row,0).toString ()))
            {
                 JOptionPane.showMessageDialog(this, "Xóa tablespace thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                 arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
            }
            else
                JOptionPane.showMessageDialog(this, "Thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_removetablespaceMouseClicked
    //refesh
    private void btn_ShowDatafileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ShowDatafileMouseClicked
        // TODO add your handling code here:
        arr = x.showDataFileAndTablespace ();
        showDataOnTable();
    }//GEN-LAST:event_btn_ShowDatafileMouseClicked
    //Thay đổi kích thuoc datafile
    private void btn_ResizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ResizeMouseClicked
        // TODO add your handling code here:
         if(txt_Linkfile.getText ().isEmpty ())
        {
            JOptionPane.showMessageDialog(this, "Lỗi kích thước nhé","Lỗi kích thước",JOptionPane.ERROR_MESSAGE);
        }else
         {
              if(t.resizeDatafile (txt_Linkfile.getText(),txt_Size.getText()))
              {
                 JOptionPane.showMessageDialog(this, "Thay đổi kích thước thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                 txt_Nametablespace.setText ("");
                  arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
              }
              else
              {
                  JOptionPane.showMessageDialog(this, "Thất bại","Lỗi tạo",JOptionPane.ERROR_MESSAGE);
              }
         }
        
    }//GEN-LAST:event_btn_ResizeMouseClicked
    //Xóa datafle
    private void btn_removeDatafileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_removeDatafileMouseClicked
        // TODO add your handling code here:
            int row = Table_Tablespace.getSelectedRow ();
            if(t.dropDataFileTablespace (txt_Linkfile.getText(), Table_Tablespace.getValueAt (row,0).toString ()) || absolutePath.isBlank ()|| absolutePath.isEmpty ())
            {
                JOptionPane.showMessageDialog(this, "Xóa datafile thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                arr = x.showDataFileAndTablespace ();
                  showDataOnTable();
             }
            else
                JOptionPane.showMessageDialog(this, "Thất bại","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_removeDatafileMouseClicked

    private void txt_DiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DiskActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Tablespace;
    private javax.swing.JButton btn_Resize;
    private javax.swing.JButton btn_ShowDatafile;
    private javax.swing.JButton btn_addDatafile;
    private javax.swing.JButton btn_changeName;
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_openFile;
    private javax.swing.JButton btn_removeDatafile;
    private javax.swing.JButton btn_removetablespace;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbb_showTablespace;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_SumDatafile;
    private javax.swing.JLabel lbl_SumTablespace;
    private javax.swing.JRadioButton rdo_Tablespace;
    private javax.swing.JRadioButton rdo_existDatafile;
    private javax.swing.JRadioButton rdo_newDatafile;
    private javax.swing.JRadioButton rdo_tablespaceDatafile;
    private javax.swing.JTextField txt_Disk;
    private javax.swing.JTextField txt_Linkfile;
    private javax.swing.JTextField txt_Nametablespace;
    private javax.swing.JTextField txt_Size;
    // End of variables declaration//GEN-END:variables
}
