/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.TimKiem;

import BLL.CallExecute;
import BLL.GetData;
import BLL.GetValue;
import DTO.SanPhamDTO;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phatl
 */
public class TimKiem extends javax.swing.JPanel {

    /**
     * Creates new form TimKiem
     */
    public TimKiem() {
        initComponents();
        loadComboBoxLoaiMon();
    }
    
    private void loadComboBoxLoaiMon(){
        GetData x = new GetData();
        Object[][] t = x.getDataLoaiMon();
        for(int i =0;i<t.length;i++)
            cbLoai.addItem(t[i][0].toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new Ultilities.swing.Controls.Table();
        txt_TimKiem = new javax.swing.JTextField();
        btnTim = new Ultilities.swing.Controls.buttonCustom();
        cbLoai = new Ultilities.swing.Controls.ComboBoxSuggestion();

        setMinimumSize(new java.awt.Dimension(785, 607));
        setPreferredSize(new java.awt.Dimension(785, 607));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM SẢN PHẨM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSanPham);

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnTim.setText("Tìm");
        btnTim.setBorderColor(new java.awt.Color(153, 204, 255));
        btnTim.setColor(new java.awt.Color(153, 204, 255));
        btnTim.setColorClick(new java.awt.Color(204, 255, 255));
        btnTim.setColorOver(new java.awt.Color(102, 204, 255));
        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        cbLoai.setMinimumSize(new java.awt.Dimension(154, 31));
        cbLoai.setPreferredSize(new java.awt.Dimension(154, 31));
        cbLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbSanPham.getModel();
        Vector<String> col = new Vector<String>();
        col.add("Mã Món");
        col.add("Tên Món");
        col.add("Giá");
        col.add("Kich Cỡ");
        col.add("Trạng Thái");
        model.setDataVector(CallExecute.callTimKiemSanPham(txt_TimKiem.getText()),col);
    }//GEN-LAST:event_btnTimActionPerformed

    private void cbLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiItemStateChanged
        String kq = evt.getItem().toString();
        GetValue x = new GetValue();
        String maLoai = x.getMaLoaiMon(kq);
        
        DefaultTableModel model = (DefaultTableModel)tbSanPham.getModel();
        Vector<String> col = new Vector<String>();
        col.add("Mã Món");
        col.add("Tên Món");
        col.add("Giá");
        col.add("Kich Cỡ");
        col.add("Trạng Thái");
        model.setDataVector(CallExecute.callTimKiemSanPhamTheoLoai(maLoai),col);
    }//GEN-LAST:event_cbLoaiItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.buttonCustom btnTim;
    private Ultilities.swing.Controls.ComboBoxSuggestion cbLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Ultilities.swing.Controls.Table tbSanPham;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
