/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.ProfileUI;

import BLL.ExecuteData;
import GUI.SystemForm;
import javax.swing.JOptionPane;

/**
 *
 * @author phatl
 */
public class CreateProfile extends javax.swing.JFrame {

    /**
     * Creates new form CreateProfile
     */
    public CreateProfile() {
        initComponents();
        loadCombobox();
    }

    public SystemForm root = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String[] items = {"UNLIMITED","DEFAULT","n"};
    
    private void loadCombobox(){
        for(var e : items){
            cb_IdelTime.addItem(e);
            cb_LoginAttempts.addItem(e);
            cb_PassLifeTime.addItem(e);
            cb_Session.addItem(e);
        }
    }
    
    private void openEditTextBox(String state, javax.swing.JTextField txt){
        if(state.equalsIgnoreCase("n")){
            txt.setEditable(true);
        }else
            txt.setEditable(false);
    }
    
    private String getValueField( javax.swing.JTextField txt, javax.swing.JComboBox<String> cb){
        String valueCb = cb.getSelectedItem().toString();
        if(valueCb.equals("n"))
            return txt.getText();
        else
            return valueCb;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_NameProfile = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_Session = new javax.swing.JComboBox<>();
        txt_SessionPerUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_LoginAttempts = new javax.swing.JComboBox<>();
        txt_FailLoginAttempt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_PassLifeTime = new javax.swing.JComboBox<>();
        txt_PassLifeTime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_IdelTime = new javax.swing.JComboBox<>();
        txt_IdelTime = new javax.swing.JTextField();
        btn_Tao = new Ultilities.swing.Controls.ButtonGradient();
        btn_Huy = new Ultilities.swing.Controls.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TẠO PROFILE");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(5, 3, 10, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NAME PROFILE");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);
        jPanel2.add(txt_NameProfile);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setEnabled(false);
        jTextField1.setOpaque(true);
        jTextField1.setPreferredSize(new java.awt.Dimension(34, 26));
        jPanel2.add(jTextField1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SESSIONS PER USER");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel3);

        cb_Session.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_Session.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_SessionItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_Session);

        txt_SessionPerUser.setEditable(false);
        txt_SessionPerUser.setPreferredSize(new java.awt.Dimension(20, 22));
        jPanel2.add(txt_SessionPerUser);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FAILED LOGIN ATTEMPTS");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel5);

        cb_LoginAttempts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_LoginAttempts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_LoginAttemptsItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_LoginAttempts);

        txt_FailLoginAttempt.setEditable(false);
        jPanel2.add(txt_FailLoginAttempt);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PASSWORD LIFE TIME");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4);

        cb_PassLifeTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_PassLifeTime.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_PassLifeTimeItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_PassLifeTime);

        txt_PassLifeTime.setEditable(false);
        jPanel2.add(txt_PassLifeTime);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("IDLE TIME");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel7);

        cb_IdelTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_IdelTime.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_IdelTimeItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_IdelTime);

        txt_IdelTime.setEditable(false);
        jPanel2.add(txt_IdelTime);

        btn_Tao.setText("Xác Nhận");
        btn_Tao.setColor2(new java.awt.Color(51, 102, 255));
        btn_Tao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Tao.setSizeSpeed(5.0F);
        btn_Tao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoActionPerformed(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.setColor1(new java.awt.Color(255, 0, 153));
        btn_Huy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Huy.setSizeSpeed(5.0F);
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Tao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_Tao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoActionPerformed
        String nameProfile = txt_NameProfile.getText();
        String sessionPer = getValueField(txt_SessionPerUser, cb_Session);
        String failLoginAttempts = getValueField(txt_FailLoginAttempt, cb_LoginAttempts);
        String passLifetime = getValueField(txt_PassLifeTime, cb_PassLifeTime);
        String IdleTime = getValueField(txt_IdelTime, cb_IdelTime);
        
        if(ExecuteData.CreateProfile(nameProfile, sessionPer, failLoginAttempts, passLifetime, IdleTime))
        {
            JOptionPane.showMessageDialog(this, "Tạo Profile " +nameProfile+" thành công !");
            root.loadDataProfile();
        }
        else
            JOptionPane.showMessageDialog(this, "Tạo Profile " +nameProfile+" thất bại !");
    }//GEN-LAST:event_btn_TaoActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void cb_SessionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_SessionItemStateChanged
        openEditTextBox(evt.getItem().toString(),txt_SessionPerUser);
    }//GEN-LAST:event_cb_SessionItemStateChanged

    private void cb_LoginAttemptsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_LoginAttemptsItemStateChanged
        openEditTextBox(evt.getItem().toString(),txt_FailLoginAttempt);
    }//GEN-LAST:event_cb_LoginAttemptsItemStateChanged

    private void cb_PassLifeTimeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_PassLifeTimeItemStateChanged
        openEditTextBox(evt.getItem().toString(),txt_PassLifeTime);
    }//GEN-LAST:event_cb_PassLifeTimeItemStateChanged

    private void cb_IdelTimeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_IdelTimeItemStateChanged
        openEditTextBox(evt.getItem().toString(),txt_IdelTime);
    }//GEN-LAST:event_cb_IdelTimeItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Ultilities.swing.Controls.ButtonGradient btn_Huy;
    private Ultilities.swing.Controls.ButtonGradient btn_Tao;
    private javax.swing.JComboBox<String> cb_IdelTime;
    private javax.swing.JComboBox<String> cb_LoginAttempts;
    private javax.swing.JComboBox<String> cb_PassLifeTime;
    private javax.swing.JComboBox<String> cb_Session;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_FailLoginAttempt;
    private javax.swing.JTextField txt_IdelTime;
    private javax.swing.JTextField txt_NameProfile;
    private javax.swing.JTextField txt_PassLifeTime;
    private javax.swing.JTextField txt_SessionPerUser;
    // End of variables declaration//GEN-END:variables
}
